<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0AG0V8V" ignored="0" name="Test" tests="5" failures="1" timestamp="28 Oct 2019 20:03:33 GMT" time="0.096" errors="0">
  <testcase name="test1" time="0.027" classname="com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest">
    <failure type="java.lang.AssertionError" message="Addition Problem! 2+2 must be 4!
 expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: Addition Problem! 2+2 must be 4!
 expected [5] but found [4]
at com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest.test1(SampleTest.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="com.RetryFailedTestsWithTestNGAtSuitLevel.SampleTest"/>
</testsuite> <!-- Test -->
