<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-0AG0V8V" name="com.TestNGListeners.SampleTest" tests="6" failures="0" timestamp="29 Oct 2019 02:14:20 GMT" time="0.044" errors="1">
  <testcase name="test4" time="0.003" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.005" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test4" time="0.016" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test2" time="0.005" classname="com.TestNGListeners.SampleTest">
    <error type="org.testng.TestException" message="
Method SampleTest.test2()[pri:0, instance:com.TestNGListeners.SampleTest@27efef64] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method SampleTest.test2()[pri:0, instance:com.TestNGListeners.SampleTest@27efef64] should have thrown an exception of type class java.lang.RuntimeException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1140)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.010" classname="com.TestNGListeners.SampleTest"/>
  <testcase name="test3" time="0.005" classname="com.TestNGListeners.SampleTest">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- com.TestNGListeners.SampleTest -->
